Us3 guests page front end
a-quelle/SETrackHotelApp pull request #10
Opened 2017-11-22 15:18 UTC by Zeffuri

2017-11-23 08:40 UTC, Briinah commented
![image](https://user-images.githubusercontent.com/11330327/33164249-399a8ff6-d032-11e7-8910-84fb2272d3ae.png

Ik heb nog wat problemen met de localdate

2017-11-23 14:26 UTC, cgilbers requested changes
Je moet nog javadoc comment toevoegen aan je guest controller

2017-11-24 12:50 UTC, cgilbers approved these changes

2017-11-24 12:53 UTC, capgeminiKoen approved these changes
Fixed some buttons, but after that, things are mighty fine

2017-11-24 12:53 UTC, merged